
[functions.revenuecat-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/revenuecat-webhook/deno.json"
entrypoint = "./functions/revenuecat-webhook/index.ts"

[functions.auth-callback]
enabled = true
verify_jwt = false
entrypoint = "./functions/auth-callback/index.ts"

[functions.auth-success]
enabled = true
verify_jwt = false
entrypoint = "./functions/auth-success/index.ts"
